services:
  - type: web
    name: polling-app-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
